
##### Setxkbmap #####
# setxkbmap -layout us,ara -variant ,digits -option grp:alt_space_toggle caps:swapescape &

##### Sxhkd #####
# sxhkd &	

##### Polkit agent  ######
# /usr/libexec/polkit-gnome-authentication-agent-1 &

##### Xrandr #####
# xrandr --output HDMI-1 --mode 1920x1080 &
# xrdb .config/Xresources

##### Xcompmgr #####
# xcompmgr -c &

##### Dwm Blocks #####
# dwmblocks &
# slstatus &

###### Pipwewire start ######
# pipewire &
# pipewire-pulse &
# wireplumber &

###### Picom ######
# picom &
# picom --experimental-backends &

###### Feh Wallpaper ######
# $HOME/.fehbg &

# exec dwm
